<p>Merge is a website that allows groups to find the optimum time to meet by leveraging the Google Calendar API.</p>
<h3>Setting Up</h3>
<p>Like pset7 and pset8, this website was written in PHP on the CS50 appliance, though it is also now accessible online. Setup requires you to extract the files into a folder called localhost in the vhosts folder; the Google API is quite persnickety, and has its redirect URI set as &ldquo;http://localhost/user.php.&rdquo; If the page isn&rsquo;t present at exactly that place on the server, it won&rsquo;t work! The Merge database, stored in a file in the main folder, should be imported via phpmyadmin. Once all of this is done, that should be enough &mdash; the website is set up!</p>
<h3>Getting Started</h3>
<p>It&rsquo;s a lot simpler to log into Merge than it is to log into many other websites. By clicking on the &ldquo;Authenticate&rdquo; link, you are taken to a page which asks for your Google credentials and for permissions. From then on, Merge has access to your name, email, and Google Calendar, though not anything else. Logging in and out of Merge is easy and secure.</p>
<h3>Creating an Event</h3>
<p>To create an event, navigate to the &ldquo;Make Event&rdquo; page. There, you will be presented with a screen allowing you to name and describe your event, describe the dates, days of the week, and times of the day you&rsquo;d like it to occur, and finally list the emails (separated by commas) of the people you&rsquo;d like to invite. It doesn&rsquo;t matter if the people you invite are not yet registered &mdash; they, along with all your other guests, will be emailed with the information about your event.</p>
<h3>Viewing an Event</h3>
<p>To view an event, you can either click on a link in an email, or land from the &ldquo;Event List&rdquo; page. There are two possible ways to view an event &mdash; either, the event is still awaiting responses (indicated by a blue light at the top), or it has been decided upon (indicated by a green light at the top). Different information is displayed depending on the situation! The people who have been invited are displayed in gray; those who have accepted are displayed in green; and those who have declined are displayed in red.</p>
<h3>Responding to an Event</h3>
<p>This is the exciting part, and where the magic happens. Everyone can either accept or decline their invitation to an event. When the last person accepts/declines their invitation, Merge runs through everyone&rsquo;s Google Calendars to find the time when the largest proportion of the group is available, and then sends out emails to alert everyone. This is the culmination of the process, and is pretty cool!</p>
